### ISSUE TITLE
Remove versions.sh and replace it will an api call to github to get the last 2 tags and the latest beta tag

### ISSUE THREAD

**Issue by robertbaker** [Admin9705/PlexGuide-Installer#2]

**Comment by Admin9705** [comment]
good to know, will test

**Comment by Admin9705** [comment]
ya it's not about that, it also limits which versions people can pull when they goto http://versions.plexguide.com; omitting the file will prevent older downloads that are valid. this would also require another upgrade to a new whole pg as people who run current pg's will get not founds and require the nightmare upgrades again :D please reopen if there is a solid solution, but it works fine :D
