### ISSUE TITLE
Installer takes over my build

### ISSUE THREAD

**Issue by stephenc87** [Admin9705/PlexGuide-Installer#5]
installv8.sh Will select repositories for me that aren't needed and installing packages without asking me, also doesn't allow me to set a PREFIX on installtime

**Comment by robertbaker** [comment]
Invalid issue. The packages are required for PG to run.

PG is meant to be on the box where PG is the only thing running on it.

**Comment by stephenc87** [comment]
This is what I'm referring to.....
apt-get install software-properties-common -y
add-apt-repository main
add-apt-repository universe
add-apt-repository restricted
add-apt-repository multiverse
#debian
add-apt-repository non-free
add-apt-repository contrib

It is reconfiguring my system, without even asking me! Can't we just check for dependency issues and work from there?

**Comment by robertbaker** [comment]
Sure you code that.
